### ISSUE TITLE
Feature | Artoolkitx plugin-libraries downloaded by github

### ISSUE THREAD

**Issue by kalwalt** [augmentmy-world/artoolkitX.js#10]
Actually if you run the the build script without the `--dev` flag, the package can' t be downloaded, because it doesn't exist yet. I think it should be only necessary to setup the releases in github with the tags. 
Useful for people that want only to test or to try the **ArtoolkitX.js** lib without the needs to build it with emscripten, that is not necessary if you want only take a look around or developing your simple own app.

**Comment by ThorstenBux** [comment]
+1 we need to do that

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kalwalt** [comment]
ok i will do after merging  PR #2

**Comment by kalwalt** [comment]
@ThorstenBux I think i can make a first release making a zip package with the `artoolkitx.js artoolkitx.wasm and artoolkitX.api.js`  and placing it on this repo or as stated in the build script do you prefer in your ArtoolkitX repository or the official ArtoolkitX?

**Comment by ThorstenBux** [comment]
Augmentmy-world/artoolkitX would be good at least as long as we are developing it.

Your idea is that the build script will download and unpack the zip and place the files in the correct location?

**Comment by kalwalt** [comment]
You already did see here:

https://github.com/augmentmy-world/artoolkitX.js/blob/a13dd388b1ab1ab6ab9838e9d585e43c6efafe71/Source/build.sh#L59-L66

we need only to change the path, upload the libs in a zip , create the version.txt file and test all. As i finish this PR #12 i will start with this.

**Comment by kalwalt** [comment]
This is done with #13
