### ISSUE TITLE
Adding transMat and other functions related to GL matrix management

### ISSUE THREAD

**Issue by kalwalt** [augmentmy-world/artoolkitX.js#5]
I think we need these to display 3d object and other data manipulation. Looking at the old jsartoolkit5 we could think to develop a solution not only for Thrree.js but for also other 3d frameworks.

**Comment by kalwalt** [comment]
I'm working on this [branch](https://github.com/kalwalt/artoolkitX.js/tree/transMat-matrix-feature). I added `transMatToGLMat()` and `arglCameraViewRHf()` prototyped functions  and the `threejs_from_scratch` example. I can not see the model, maybe we need the getTransMatSquareCont() function?

**Comment by ThorstenBux** [comment]
Need to look into that. I had 3D content showing using an example need to dig that out.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kalwalt** [comment]
yes it's pretty boring to see only data tracking in the console :smile: !!
The simplest way to get transformation data  is now:

```js
ARController.prototype.getTransformationData = function (trackableUID) {
      return this.trackables[trackableUID].transformation;
    };

```
But the model is not moving with the marker, i have also set up the camera matrix, but maybe it is a problem hot to setup ArtoolkitX.js with Three.js. Maybe it will be better trying with a simple WebGl example.

**Comment by ThorstenBux** [comment]
I’ve dug out two examples that should show you how to do it.
I haven’t had time today to test these but last time I looked they worked.

**Comment by ThorstenBux** [comment]
The examples are merged to master now. Somehow forgot to push yesterday

**Comment by kalwalt** [comment]
Thank you Thorsten i will look into it! They are very useful, i think i was overcomplicating the code, needs only to compile 2d tracking now! :smile: 
Tomorrow i will modify the other examples.

**Comment by kalwalt** [comment]
`simple_video_2d.threeJS.hiro.html` works very fine, just need to add the three..min.js in the Data folder
`<script  type='text/javascript' src="./Data/js/third_party/three.js/three.min.js"></script>`
and i need to fix in `getCameraMatrix()`:

```diff

- return artoolkitXjs.arwGetProjectionMatrix(nearPlane, farPlane);
+ return artoolkitXjs._arwGetProjectionMatrix(nearPlane, farPlane);
 
```

**Comment by ThorstenBux** [comment]
Once you have had a look at the examples please let me know if we still need that feature. Because I imagine that other 3D libs like Babylon, Cesium WebGL directly can be utilized the same way. But I might be mistaken and too much into the current implementation

**Comment by kalwalt** [comment]
> Once you have had a look at the examples please let me know if we still need that feature. Because I imagine that other 3D libs like Babylon, Cesium WebGL directly can be utilized the same way. But I might be mistaken and too much into the current implementation

I will try with Babylon.js and maybe pure WebGl, But maybe could be used internally by the library? I will think about it.

**Comment by kalwalt** [comment]
I adapted an example https://github.com/kalwalt/artoolkitX.js/blob/transMat-matrix-feature/Examples/threejs_from_scratch.html from the jsartoolkit5 project, if i not use the shader is all right, the cube is displayed correctly, but if you choose to USE_SHADER the model is like distroyed and appear larger. Maybe the shader handle the transformation Matrix in a different way? or maybe i miss something?

**Comment by kalwalt** [comment]
We could try to develop some example with https://github.com/jagenjo/litegl.js the WebGl library used by [webglstudio](https://webglstudio.org/) as discussed in the chat it could be a nice improvement to test ArtoolkitX.js with that library. In regards to trans mat functions and other related  i think we could add `transMatToGLMat` and `arglCameraViewRHf` functions.

**Comment by kalwalt** [comment]
The `transMatToGLMat` and `arglCameraViewRHf` have been added with #23.
