### ISSUE TITLE
Cmake can not find OpenCV

### ISSUE THREAD

**Issue by kalwalt** [augmentmy-world/artoolkitX.js#8]
When i run the build script Cmake fails, for some reason, to find the OpenCV libs and the include directories. Some days ago instead i built the project ArtoolkitX project under Linux ( i mean running `./build.sh linux` in the master branch )  and cmake can find the OpenCV libs and includes. The FindOpenCV.cmake are the same ( i verified this !) and so i think the issue is somewhere in the CmakeLists.txt files.
This is not a high priority but it will become when we will be near to implement 2d tracking.
This issue as i know, seems to happens only under linux....

**Comment by ThorstenBux** [comment]
To compile ArtoolkitX.js with 2d tracking we need OpenCV and the include that we need to compile OpenCV with emscripten.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ThorstenBux** [comment]
The whole Opencv not just a part of it like opencv.js

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kalwalt** [comment]
@ThorstenBux Can you build ArtoolkitX.js with OpenCV? Do you have the same problem?

**Comment by kalwalt** [comment]
i think that this can be closed. It's not necessary the OpenCV deps at the moment.
